In [1]:
import numpy as np
import glob
import cv2
d={}

In [2]:
data_dir='editedut/*/*'
data_list=glob.glob(data_dir)
img_size=(28,28)
frame_number=20
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
label=np.empty([1,])
fps=30
sample_step=1
npz_order=0
num_cat = 2
video_per_cat=14


print(len(data_list))
print(data.shape)


29
(1, 20, 28, 28, 3)


In [3]:
with open("classIndVio.txt") as f:
    for line in f:
       (key, val) = line.split()
       d[int(key)-1] = val

In [4]:
one_hot_array = np.zeros((1,num_cat))

In [5]:
videonumkeeptrack = np.zeros((1,num_cat))


In [6]:
arraynum = 0
for num, video in enumerate(data_list):
    read_video = False
    print (num, video)

    for key, videoname in d.items():    # for name, age in dictionary.iteritems():  (for Python 2.x)
        if (videoname in video):
            cap = cv2.VideoCapture(video)
            #fps = cap.get(cv2.CAP_PROP_FPS)
            total_frame=cap.get(cv2.CAP_PROP_FRAME_COUNT)
#             if(videonumkeeptrack[0][key]<video_per_cat):
#                 videonumkeeptrack[0][key] = videonumkeeptrack[0][key]+1
#                 print(videonumkeeptrack)
#                 print(video)
#                 one_hot_array[arraynum][key]=1

            sample=np.zeros([1,1,img_size[0],img_size[1],3])
            for i in range(int(total_frame)):
                if (i%sample_step)==0 and not i == 0:
                    ret, frame = cap.read()
                    if ret==False:
                        prev=sample[0,-1].reshape(1,1,img_size[0],img_size[1],3)
                        sample=np.append(sample,prev,axis=1)
                    else:
                        cropped_frame=cv2.resize(frame,(img_size[0],img_size[1]))
                        cropped_frame=cropped_frame.reshape(1,1,img_size[0],img_size[1],3)
                        sample=np.append(sample,cropped_frame,axis=1)
                        print(sample.shape)
                    if((i%(frame_number) )== 0 and (not i == 0)):
                        print("trim")
                        print(sample.shape)

                        sample = np.moveaxis(sample,1,0)
                        sample=sample[1:]
                        sample = np.moveaxis(sample,1,0)
                        print("the shape is")
                        print(sample.shape)

                        sample=sample.reshape([1,frame_number,img_size[0],img_size[1],3])
#                         #print("one sample shape: {}".format(sample.shape))
                        print(sample.shape)
                        data=np.append(data,sample,axis=0)
                        sample=np.zeros([1,1,img_size[0],img_size[1],3])

                        if("violence" in video):
                            one_hot_array = np.append(one_hot_array,[[1,0]],axis=0)
                        elif("non" in video):
                            one_hot_array = np.append(one_hot_array,[[0,1]],axis =0)
                        

#         del sample,cropped_frame

one_hot_array = one_hot_array[1:,...]
print("label shape；{}".format(one_hot_array.shape))
print("data shape；{}".format(data.shape))

0 editedut/non/non2.mp4
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28,

(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21

(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28,

(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the sh

(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
10 editedut/non/non3.mp4
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3

(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28,

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3

(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 

(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 

(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
27 editedut/violence/violence13.mp4
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(

(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 28, 3)
(1, 15, 28, 28, 3)
(1, 16, 28, 28, 3)
(1, 17, 28, 28, 3)
(1, 18, 28, 28, 3)
(1, 19, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 21, 28, 28, 3)
trim
(1, 21, 28, 28, 3)
the shape is
(1, 20, 28, 28, 3)
(1, 20, 28, 28, 3)
(1, 2, 28, 28, 3)
(1, 3, 28, 28, 3)
(1, 4, 28, 28, 3)
(1, 5, 28, 28, 3)
(1, 6, 28, 28, 3)
(1, 7, 28, 28, 3)
(1, 8, 28, 28, 3)
(1, 9, 28, 28, 3)
(1, 10, 28, 28, 3)
(1, 11, 28, 28, 3)
(1, 12, 28, 28, 3)
(1, 13, 28, 28, 3)
(1, 14, 28, 

In [7]:

raw_data = data[1:]
raw_data = raw_data/255.0
print(raw_data.shape)
print(one_hot_array.shape)

(294, 20, 28, 28, 3)
(294, 2)


In [8]:
print(raw_data)

[[[[[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.16862745 0.18039216 0.18039216]
    ...
    [0.47058824 0.49803922 0.50196078]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.11372549 0.11372549 0.11372549]
    ...
    [0.47843137 0.50588235 0.50588235]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.18431373 0.18823529 0.16470588]
    ...
    [0.5254902  0.54509804 0.54509804]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   ...

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.30196078 0.23137255 0.20784314]
    ...
    [0.45490196 0.49019608 0.49411765]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         

In [9]:
np.random.seed(42)
index=np.arange(len(one_hot_array))
np.random.shuffle(index)
print (index)
raw_data=raw_data[index]
one_hot_array=one_hot_array[index]

[ 33   9 146 282 261 125 108 206 109  42  82  46 164  56 116 225  59 185
 210   5 273 248 219 113 272  90  60 180 275  79 203 126 264 147  45 124
  63 218 292 291  84 286  25  75 277 173 278 195  30  22 242  24 154  76
  93 139  17 119 230 181 209 168   6 224 155 280  66  92 152  73  19 247
  77 283  72  15  10 112  68 117  37  16 101 137 265  67 202 165 114 118
 216  97  18 170  86 234 193 176 111 175 194  55 172 255 239  38 183 213
  57 182 158 104 221 157  31 271  78 211 140 236 266  96 177 231 200 132
 184  69 167   2 115 144 260 120 250 253 127  74  29 254 229 107 143 148
 238 178 204  65 186  85 227  12  35  28 142 179 240 159  51  95 196 208
  41  89 233 136  26 287 141 289   0 263 100 246 279 249  98  36  61 150
 223 232 228  11 290 262  27 215   4 122  32 192 162 197 244 138  62 135
 128 284   8  70 259  64  44 222 156  40 123 251 153  23 256 274  81 207
 212  39 226 285 245 199  14  47  94 258 268 201 161  43 217 145 190 220
 237   3 105  53 133   1 131 103  49 163  80 205  3

In [10]:
print(one_hot_array)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 

In [11]:
np.savez_compressed('npz_data/violence/data_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=raw_data)
np.savez_compressed('npz_data/violence/label_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=one_hot_array)
#npz_order+=1
raw_data=np.empty([1,frame_number,img_size[0],img_size[1],3])
one_hot_array=np.empty([1,num_cat])

In [12]:
print(raw_data.shape)
print(one_hot_array.shape)

(1, 20, 28, 28, 3)
(1, 2)
