In [1]:
import numpy as np
import glob
import cv2

In [2]:
data_dir='talkdata/test/*/*'
data_list=glob.glob(data_dir)
img_size=(28,28)
frame_number=20
sample_step=1
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
npz_order=0
print(len(data_list))
print(data.shape)

2
(1, 20, 28, 28, 3)


In [3]:
# import json
# with open(cat_file) as json_file:
#     cat=json.load(json_file)

In [4]:
for num, video in enumerate(data_list):
    print (num, video)
    arraynum =0
    column = 0
    switch = 0
    cap = cv2.VideoCapture(video)
    #fps = cap.get(cv2.CAP_PROP_FPS)
    total_frame=cap.get(cv2.CAP_PROP_FRAME_COUNT)
    print(total_frame)
    ret =True
    while ret ==True and arraynum<15:
        sample=np.empty([1,1,img_size[0],img_size[1],3])
        for i in range(sample_step*frame_number):
            ret, frame = cap.read()

            if (i%sample_step)==0:
                if ret==False:
                    prev=sample[0,-1].reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,prev,axis=1)
                else:
                    cropped_frame=cv2.resize(frame,(img_size[0],img_size[1]))
                    cropped_frame=cropped_frame.reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,cropped_frame,axis=1)
        sample=sample[0,1:]
        sample=sample.reshape([1,frame_number,img_size[0],img_size[1],3])
        #print("one sample shape: {}".format(sample.shape))
        data=np.append(data,sample,axis=0)
        del sample,cropped_frame
#         if "talk" in video:
#              label[arraynum*switch,0] = 1
#         elif "non" in video:
#              label[arraynum*switch,1] = 1
#      elif "Swing" in video:
#          label=np.append(label,np.array([int(2)]),axis=0)
#      elif "PushUps" in video:
#          label=np.append(label,np.array([int(3)]),axis=0)
        arraynum=arraynum+1
    switch=switch+1
    column=column+1
#     print(label.shape)

#     print("data shape；{}".format(data.shape))
    #print(label)
    
    #if (num+1)%200==0:
    
np.random.seed(42)
data=data[1:]
data = data/255.0
label = np.append(np.asarray([[1,0]]*int(data.shape[0]/2)),np.asarray([[0,1]]*int(data.shape[0]/2)),axis=0)
print(label.shape)
print(data)
print(data.shape)
index=np.arange(len(label))
np.random.shuffle(index)
#print (index)
data=data[index]
label=label[index]
np.savez_compressed('npz_data/testtalk/data_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=data)
np.savez_compressed('npz_data/testtalk/label_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=label)
#npz_order+=1
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
label=np.empty([1,])

0 talkdata/test/notchatting/notchatting.mp4
701.0
1 talkdata/test/talking/talking.mp4
915.0
(30, 2)
[[[[[0.85490196 0.81176471 0.77647059]
    [0.85882353 0.81568627 0.78039216]
    [0.8627451  0.81960784 0.78431373]
    ...
    [0.35686275 0.39215686 0.41568627]
    [0.38431373 0.36078431 0.39215686]
    [0.19215686 0.20784314 0.24313725]]

   [[0.85490196 0.81176471 0.77647059]
    [0.8627451  0.81568627 0.78823529]
    [0.8627451  0.81960784 0.78431373]
    ...
    [0.07843137 0.10196078 0.11764706]
    [0.40392157 0.40392157 0.40392157]
    [0.1254902  0.1372549  0.18039216]]

   [[0.85490196 0.80392157 0.78431373]
    [0.8627451  0.81568627 0.78823529]
    [0.8627451  0.81568627 0.78823529]
    ...
    [0.08627451 0.11764706 0.13333333]
    [0.3254902  0.31372549 0.31764706]
    [0.16470588 0.17647059 0.25098039]]

   ...

   [[0.55294118 0.52156863 0.48235294]
    [0.58431373 0.54117647 0.50196078]
    [0.61176471 0.56078431 0.51764706]
    ...
    [0.4745098  0.44313725 0.431372