In [1]:
import numpy as np
import glob
import cv2

In [2]:
data_dir='talkdata/*/*'
data_list=glob.glob(data_dir)
img_size=(28,28)
frame_number=20
sample_step=3
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
npz_order=0
print(len(data_list))
print(data.shape)

4
(1, 20, 28, 28, 3)


In [3]:
# import json
# with open(cat_file) as json_file:
#     cat=json.load(json_file)

In [4]:
for num, video in enumerate(data_list):
    print (num, video)
    arraynum =0
    column = 0
    switch = 0
    cap = cv2.VideoCapture(video)
    #fps = cap.get(cv2.CAP_PROP_FPS)
    total_frame=cap.get(cv2.CAP_PROP_FRAME_COUNT)
    #print(total_frame)
    ret =True
    while ret ==True and arraynum<100:
        sample=np.empty([1,1,img_size[0],img_size[1],3])
        for i in range(sample_step*frame_number):
            ret, frame = cap.read()

            if (i%sample_step)==0:
                if ret==False:
                    prev=sample[0,-1].reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,prev,axis=1)
                else:
                    cropped_frame=cv2.resize(frame,(img_size[0],img_size[1]))
                    cropped_frame=cropped_frame.reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,cropped_frame,axis=1)
        sample=sample[0,1:]
        sample=sample.reshape([1,frame_number,img_size[0],img_size[1],3])
        #print("one sample shape: {}".format(sample.shape))
        data=np.append(data,sample,axis=0)
        del sample
#         if "talk" in video:
#              label[arraynum*switch,0] = 1
#         elif "non" in video:
#              label[arraynum*switch,1] = 1
#      elif "Swing" in video:
#          label=np.append(label,np.array([int(2)]),axis=0)
#      elif "PushUps" in video:
#          label=np.append(label,np.array([int(3)]),axis=0)
        arraynum=arraynum+1
    switch=switch+1
    column=column+1
#     print(label.shape)

#     print("data shape；{}".format(data.shape))
    #print(label)
    
    #if (num+1)%200==0:
    
np.random.seed(42)
data=data[1:]
data = data/255.0
label = np.append(np.asarray([[1,0]]*int(data.shape[0]/2)),np.asarray([[0,1]]*int(data.shape[0]/2)),axis=0)
print(label.shape)
print(data)
print(data.shape)
index=np.arange(len(label))
np.random.shuffle(index)
#print (index)
data=data[index]
label=label[index]
np.savez_compressed('npz_data/talk/data_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=data)
np.savez_compressed('npz_data/talk/label_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=label)
#npz_order+=1
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
label=np.empty([1,])

0 talkdata/notchatting/notchatting.mp4
1 talkdata/talking/talking.mp4
2 talkdata/test/notchatting
3 talkdata/test/talking
(202, 2)
[[[[[5.29411765e-001 5.76470588e-001 6.03921569e-001]
    [1.56862745e-001 1.68627451e-001 1.60784314e-001]
    [1.37254902e-001 1.49019608e-001 1.41176471e-001]
    ...
    [3.09803922e-001 4.03921569e-001 4.43137255e-001]
    [2.94117647e-001 3.88235294e-001 4.27450980e-001]
    [2.70588235e-001 3.64705882e-001 4.03921569e-001]]

   [[5.37254902e-001 5.80392157e-001 6.11764706e-001]
    [1.68627451e-001 1.80392157e-001 1.72549020e-001]
    [1.64705882e-001 1.76470588e-001 1.68627451e-001]
    ...
    [4.07843137e-001 4.78431373e-001 4.86274510e-001]
    [4.11764706e-001 4.86274510e-001 5.21568627e-001]
    [4.47058824e-001 5.09803922e-001 5.37254902e-001]]

   [[5.29411765e-001 5.72549020e-001 6.03921569e-001]
    [1.33333333e-001 1.45098039e-001 1.37254902e-001]
    [1.68627451e-001 1.80392157e-001 1.72549020e-001]
    ...
    [4.31372549e-001 5.29411765