# Using your own object detector for detection images

This notebook is based on the [official Tensorflow Object Detection demo](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) and only contains some slight changes. Make sure to follow the [installation instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) before you start.

# Imports

In [1]:
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from distutils.version import StrictVersion
from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")
from object_detection.utils import ops as utils_ops

if StrictVersion(tf.__version__) < StrictVersion('1.9.0'):
  raise ImportError('Please upgrade your TensorFlow installation to v1.9.* or later!')

## Env setup

In [2]:
# This is needed to display the images.
%matplotlib inline

## Object detection imports
Here are the imports from the object detection module.

In [3]:
from object_detection.utils import label_map_util

from object_detection.utils import visualization_utils as vis_util

# Model preparation 

## Variables

Any model exported using the `export_inference_graph.py` tool can be loaded here simply by changing `PATH_TO_FROZEN_GRAPH` to point to a new .pb file.  

In [4]:
MODEL_NAME = 'inference_graph'
PATH_TO_FROZEN_GRAPH = 'trained-inference-graphs/output_inference_graph_v1.pb/frozen_inference_graph.pb'
PATH_TO_LABELS = 'annotations/label_map.pbtxt'

## Load a (frozen) Tensorflow model into memory.

In [5]:
detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

## Loading label map
Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine

In [6]:
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

# Detection

In [7]:
def run_inference_for_single_image(image, graph):
    if 'detection_masks' in tensor_dict:
        # The following processing is only for single image
        detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
        detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
        # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
        real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
        detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
        detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            detection_masks, detection_boxes, image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(
            tf.greater(detection_masks_reframed, 0.5), tf.uint8)
        # Follow the convention by adding back the batch dimension
        tensor_dict['detection_masks'] = tf.expand_dims(
            detection_masks_reframed, 0)
    image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

    # Run inference
    output_dict = sess.run(tensor_dict,
                            feed_dict={image_tensor: np.expand_dims(image, 0)})

    # all outputs are float32 numpy arrays, so convert types as appropriate
    output_dict['num_detections'] = int(output_dict['num_detections'][0])
    output_dict['detection_classes'] = output_dict[
        'detection_classes'][0].astype(np.uint8)
    output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
    output_dict['detection_scores'] = output_dict['detection_scores'][0]
    if 'detection_masks' in output_dict:
        output_dict['detection_masks'] = output_dict['detection_masks'][0]
    return output_dict

In [23]:
# def multiply(x):
#     return x * 800


# import cv2
# cap = cv2.VideoCapture("test2.mp4")
# try:
#     with detection_graph.as_default():
#         with tf.Session() as sess:
#                 # Get handles to input and output tensors
#                 ops = tf.get_default_graph().get_operations()
#                 all_tensor_names = {output.name for op in ops for output in op.outputs}
#                 tensor_dict = {}
#                 for key in [
#                   'num_detections', 'detection_boxes', 'detection_scores',
#                   'detection_classes', 'detection_masks'
#                 ]:
#                     tensor_name = key + ':0'
#                     if tensor_name in all_tensor_names:
#                         tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
#                       tensor_name)

#                 while True:
#                     ret, image_np = cap.read()
#                     # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
#                     image_np_expanded = np.expand_dims(image_np, axis=0)
#                     # Actual detection.
#                     output_dict = run_inference_for_single_image(image_np, detection_graph)
#                     coordinates = np.asarray(output_dict['detection_boxes'])*800
#                     print(np.asarray(coordinates))
                    
#                     cv2.rectangle(image_np, (int(coordinates[-1][1]), int(coordinates[-1][0])), (int(coordinates[-1][3]), int(coordinates[-1][2])), (255,0,0), 2)
#                     # Visualization of the results of a detection.
#                     vis_util.visualize_boxes_and_labels_on_image_array(
#                         image_np,
#                         output_dict['detection_boxes'],
#                         output_dict['detection_classes'],
#                         output_dict['detection_scores'],
#                         category_index,
#                         instance_masks=output_dict.get('detection_masks'),
#                         use_normalized_coordinates=True,
#                         line_thickness=8)
#                     cv2.imshow('object_detection', cv2.resize(image_np, (800, 800)))
#                     if cv2.waitKey(25) & 0xFF == ord('q'):
#                         cap.release()
#                         cv2.destroyAllWindows()
#                         break
# except Exception as e:
#     print(e)
#     cap.release()

[[ 74.37456  192.6086   577.61115  378.03674 ]
 [550.3731   105.84693  800.       302.61246 ]
 [  0.       477.09918  554.591    800.      ]
 [  0.       335.48788  316.731    800.      ]
 [285.6921     0.       800.       286.19485 ]
 [403.43634  567.0982   800.       800.      ]
 [413.23672  460.80228  800.       800.      ]
 [415.1269   258.03458  800.       574.46814 ]
 [307.46088  363.36536  599.6684   658.45557 ]
 [629.0192   192.26633  800.       513.196   ]
 [330.18497  395.41873  800.       738.77203 ]
 [514.3258   196.59383  800.       383.86954 ]
 [  0.       371.71103  373.67557  800.      ]
 [  0.         0.       128.98935  566.8837  ]
 [242.45288  341.47495  659.6622   800.      ]
 [592.52026  427.42444  800.       800.      ]
 [473.3634   311.40784  787.53845  800.      ]
 [454.7903   504.27414  800.       702.69244 ]
 [  0.         0.       408.50867  360.79965 ]
 [527.2754   387.90845  800.       641.6728  ]
 [450.37814  168.3025   800.       660.5526  ]
 [  0.       

[[ 78.491684 190.93852  589.4601   378.37662 ]
 [549.2476   107.13793  800.       304.4565  ]
 [  0.       477.658    560.44324  800.      ]
 [  0.       331.54358  316.27057  800.      ]
 [280.2108     0.       800.       288.37537 ]
 [626.7549   190.80038  800.       512.5001  ]
 [404.15182  566.2378   800.       800.      ]
 [411.33533  459.94617  800.       800.      ]
 [328.70102  393.9956   800.       739.9203  ]
 [413.1931   259.71597  800.       573.63965 ]
 [515.89557  196.1736   800.       387.8381  ]
 [452.87314  504.30508  800.       701.6259  ]
 [  0.         0.       128.01971  603.8118  ]
 [591.97296  428.42703  800.       800.      ]
 [  0.         0.       406.56635  361.80563 ]
 [586.8722    82.020905 800.       486.02737 ]
 [524.27826  387.7734   800.       641.638   ]
 [  0.       367.66156  366.61368  800.      ]
 [  0.         0.       267.7129   539.1795  ]
 [472.73102  316.417    784.5113   800.      ]
 [410.28165  366.14935  731.1098   800.      ]
 [306.3931   

[[552.5362    102.56786   800.        300.51492  ]
 [  0.        331.63675   315.79288   800.       ]
 [ 80.55487   192.81297   581.59485   378.23547  ]
 [  0.        477.83228   558.8069    800.       ]
 [281.90955     0.        800.        289.7021   ]
 [405.52014   566.6483    800.        800.       ]
 [626.7911    188.10619   800.        512.155    ]
 [411.7147    459.5531    800.        800.       ]
 [  0.          0.        127.05328   584.14764  ]
 [324.2037    392.9885    800.        738.563    ]
 [407.17908   260.77237   800.        573.68665  ]
 [514.6443    194.8324    800.        384.24677  ]
 [  0.          0.        408.45203   363.1035   ]
 [456.0423    503.853     800.        700.3746   ]
 [591.72656   430.47247   800.        800.       ]
 [  0.          0.        269.0057    541.051    ]
 [525.32367   385.91092   800.        639.4374   ]
 [410.63293    65.878525  800.        405.71603  ]
 [470.97015   320.8447    782.01587   800.       ]
 [ 63.56697    72.9385    519.9

[[ 85.78048   189.27817   583.8855    378.5747   ]
 [551.0908    103.84774   800.        305.149    ]
 [  0.        320.23096   320.63446   800.       ]
 [  0.        477.46545   556.70276   800.       ]
 [279.02426     0.        800.        289.76154  ]
 [411.059     458.71667   800.        800.       ]
 [403.44333   565.95776   800.        800.       ]
 [624.7744    190.2638    800.        508.6411   ]
 [336.7882    389.44763   800.        741.6963   ]
 [409.385     262.18683   800.        570.01685  ]
 [469.633     310.92722   784.2964    800.       ]
 [534.76685   441.59564   800.        800.       ]
 [511.19427   194.90845   800.        384.36624  ]
 [  0.          0.        143.80026   575.7459   ]
 [  0.          0.        412.19846   357.50543  ]
 [242.1619    327.03516   671.1415    800.       ]
 [524.6021    384.01685   800.        641.17523  ]
 [  0.        365.5905    364.32855   800.       ]
 [589.3283     82.23672   800.        490.10272  ]
 [405.95245   360.91946   736.1

[[550.58276  102.44948  800.       305.897   ]
 [  0.       324.83743  321.6034   800.      ]
 [ 79.12686  192.0448   594.2181   377.92957 ]
 [  0.       481.8553   559.0605   800.      ]
 [410.2727   460.57614  800.       800.      ]
 [275.6685     0.       800.       291.3129  ]
 [400.5477   566.0143   800.       800.      ]
 [621.16113  186.8638   800.       508.15338 ]
 [511.57837  196.29492  800.       383.24118 ]
 [468.5523   306.1445   785.5464   800.      ]
 [340.7912   389.76813  800.       741.1282  ]
 [588.72864   77.24478  800.       489.08377 ]
 [  0.         0.       416.46585  358.03305 ]
 [299.86487  356.51807  598.301    663.6315  ]
 [407.88504  262.38593  800.       571.0276  ]
 [404.83722  359.05295  734.4723   800.      ]
 [244.52626  330.24774  664.01465  800.      ]
 [532.52264  442.81082  800.       800.      ]
 [  0.         0.       271.73776  565.36084 ]
 [  0.       364.83783  360.17633  800.      ]
 [152.76341   89.00774  661.3277   285.3565  ]
 [524.20996  

[[555.07874  103.88455  800.       302.74524 ]
 [  0.       317.3919   328.33356  800.      ]
 [275.9231     0.       800.       291.1397  ]
 [406.12592  458.33664  800.       800.      ]
 [ 83.799835 192.04778  596.95776  377.49448 ]
 [  0.       482.37048  560.4482   800.      ]
 [399.71265  564.4538   800.       800.      ]
 [468.89157  290.21524  792.9298   800.      ]
 [  0.         0.       412.54025  357.13104 ]
 [519.00024  197.5579   800.       383.21902 ]
 [351.35883  389.69427  800.       746.1416  ]
 [591.9243   416.23373  800.       800.      ]
 [240.82141  322.27292  662.87305  800.      ]
 [587.5892    82.375786 800.       488.17014 ]
 [  0.         0.       276.08414  575.4481  ]
 [620.97327  189.39812  800.       507.00583 ]
 [  0.        64.65628  267.5016   687.76685 ]
 [401.26358  350.8545   737.9207   800.      ]
 [  0.       369.2144   363.5868   800.      ]
 [409.82703  258.249    800.       571.32227 ]
 [626.506     12.513388 800.       355.2758  ]
 [439.55984  

[[304.67502  366.84445  586.5903   652.6222  ]
 [556.3816   106.30154  800.       305.03906 ]
 [ 87.452484 193.93384  573.90796  376.87085 ]
 [280.47073    0.       800.       290.17874 ]
 [408.27393  457.95245  800.       800.      ]
 [400.73206  563.5284   800.       800.      ]
 [  0.       478.57724  562.3325   800.      ]
 [518.6798   197.91608  800.       384.05142 ]
 [  0.       327.20123  317.18918  800.      ]
 [405.0132   351.3594   728.4425   800.      ]
 [592.15405  420.93076  800.       800.      ]
 [330.78815  399.3751   800.       738.43005 ]
 [417.43497  253.02878  800.       580.7788  ]
 [454.65793    0.       754.0295   154.10385 ]
 [470.72858  307.54068  791.7758   800.      ]
 [629.76294  189.58998  800.       516.34143 ]
 [586.86255   79.53756  800.       486.60098 ]
 [442.92874  100.88918  800.       286.1588  ]
 [350.3873   378.69635  701.7975   672.01    ]
 [453.76797  504.3531   800.       701.9083  ]
 [529.72534  387.3207   800.       645.5051  ]
 [624.7536   

[[551.4645    105.24705   800.        302.28888  ]
 [310.86115   376.41464   590.0832    650.28345  ]
 [515.43585   196.79854   800.        382.45624  ]
 [  0.        482.77725   563.1707    800.       ]
 [283.23718     0.        800.        287.04654  ]
 [  0.        339.21802   316.10785   800.       ]
 [629.17126    12.291992  800.        354.2554   ]
 [441.16864   103.67408   800.        284.56448  ]
 [401.282     562.88794   800.        800.       ]
 [592.151      79.69718   800.        487.13913  ]
 [409.41077   461.2231    800.        800.       ]
 [630.7979    186.7723    800.        518.8025   ]
 [472.15985   310.70312   797.033     800.       ]
 [ 86.75308   192.75813   585.2031    372.3789   ]
 [536.5116    448.5673    800.        800.       ]
 [452.62094     0.        757.3382    160.80243  ]
 [407.2301    351.735     724.546     800.       ]
 [  0.          0.        414.66254   366.46777  ]
 [245.76192   339.65347   649.9948    800.       ]
 [353.94806   385.85257   697.9

[[552.01556   104.22275   800.        300.51068  ]
 [308.4261    376.71906   590.53485   654.4526   ]
 [517.3091    196.9572    800.        381.9317   ]
 [595.8086     80.4327    800.        482.03522  ]
 [442.82513   102.850746  800.        283.4895   ]
 [280.99072     0.        800.        285.782    ]
 [397.92944   561.7484    800.        800.       ]
 [628.6971     10.166883  800.        353.09955  ]
 [  0.        332.45123   321.62796   800.       ]
 [630.49786   186.17296   800.        515.1052   ]
 [407.89252   461.21558   800.        800.       ]
 [ 70.71726   195.16159   598.4424    372.6708   ]
 [  0.        483.7904    563.7744    800.       ]
 [472.60104   301.77832   800.        800.       ]
 [  0.         71.29743   274.18637   683.09186  ]
 [  0.          0.        315.33328   268.91748  ]
 [535.62695   445.47357   800.        800.       ]
 [  0.          0.        165.05115   577.205    ]
 [405.4747    351.36157   725.0466    800.       ]
 [144.31319    89.44678   660.1

[[548.0014    104.533264  800.        305.08444  ]
 [522.3624    196.61305   800.        384.275    ]
 [309.70444   383.1739    590.5034    649.51855  ]
 [ 81.166504  193.95062   586.43915   373.7265   ]
 [627.8507    183.90147   800.        517.54834  ]
 [284.06314     0.        800.        286.1577   ]
 [400.36478   562.9175    800.        800.       ]
 [407.1087    462.44202   800.        800.       ]
 [438.342     103.206696  800.        284.53674  ]
 [  0.        337.19107   318.00342   800.       ]
 [585.2187     83.38194   800.        480.57852  ]
 [  0.        480.75308   564.96906   800.       ]
 [534.48254   448.35382   800.        800.       ]
 [457.95288     0.        757.2047    158.82495  ]
 [448.93915   504.4203    800.        704.3106   ]
 [473.4398    312.00845   797.3579    800.       ]
 [319.14056   404.6057    800.        736.5133   ]
 [ 95.29717   101.39115   575.79114   265.1603   ]
 [405.842     356.00272   725.0207    800.       ]
 [527.4537    389.6024    800. 

[[552.10364  104.66866  800.       303.39197 ]
 [306.0458   379.50922  590.50696  653.46063 ]
 [524.4415   197.00833  800.       384.09238 ]
 [626.55914  188.31145  800.       514.9831  ]
 [  0.       479.7838   565.337    800.      ]
 [  0.       334.41702  319.84195  800.      ]
 [285.30133    0.       800.       285.06497 ]
 [400.163    563.21576  800.       800.      ]
 [ 79.8137   190.18585  586.2476   378.76407 ]
 [407.4358   462.4218   800.       800.      ]
 [446.6116   103.74365  800.       283.9451  ]
 [534.4076   448.37656  800.       800.      ]
 [588.52454   80.94983  800.       480.99603 ]
 [472.50525  307.58255  798.0724   800.      ]
 [631.15967   10.97616  800.       350.59686 ]
 [451.60657  504.40765  800.       704.2661  ]
 [322.80768  403.88428  800.       738.61334 ]
 [527.1274   390.31052  800.       645.41315 ]
 [405.37323  346.09818  725.026    800.      ]
 [449.2073   158.3672   800.       658.12585 ]
 [135.19235   82.841095 671.4273   291.03403 ]
 [419.16675  

[[554.4947    104.532364  800.        302.18756  ]
 [519.322     198.69685   800.        382.7795   ]
 [303.93008   382.04733   595.7096    652.4422   ]
 [  0.        478.7335    565.21094   800.       ]
 [283.67535     0.        800.        286.1915   ]
 [628.2228    187.58978   800.        516.44415  ]
 [439.90125   102.88329   800.        281.52502  ]
 [586.3265     81.28168   800.        480.99536  ]
 [  0.        339.47412   315.0913    800.       ]
 [402.59952   562.83246   800.        800.       ]
 [408.06345   461.07922   800.        800.       ]
 [ 66.96131   192.99727   585.4578    374.4      ]
 [534.52246   448.4841    800.        800.       ]
 [472.7689    311.45297   796.5839    800.       ]
 [632.5785     12.603688  800.        352.89822  ]
 [320.3441    403.87402   800.        738.3353   ]
 [405.8109    347.14465   725.3359    800.       ]
 [451.39798   504.80627   800.        704.11383  ]
 [ 98.87583   103.49763   563.0593    264.65152  ]
 [450.4435    155.33397   800. 

[[552.04285   105.586365  800.        301.58408  ]
 [308.84494   381.2183    590.40955   660.3722   ]
 [512.95416   197.16705   800.        384.59192  ]
 [629.99725   188.53452   800.        516.14514  ]
 [  0.        475.28333   562.01984   800.       ]
 [  0.        343.7238    311.80704   800.       ]
 [591.05524    80.591225  800.        480.39923  ]
 [283.43283     0.        800.        286.3789   ]
 [409.30008   462.1749    800.        800.       ]
 [402.35544   563.6184    800.        800.       ]
 [ 80.30374   193.25116   578.4839    375.49646  ]
 [443.03464   104.06712   800.        284.8192   ]
 [537.2474    454.38928   800.        800.       ]
 [448.91858   504.54532   800.        705.74615  ]
 [630.8072      9.865069  800.        351.7979   ]
 [148.4519     83.03698   672.4028    291.06937  ]
 [407.97424   354.17377   723.3382    800.       ]
 [415.48428   251.88565   800.        579.3671   ]
 [460.7932      0.        754.87573   153.40045  ]
 [469.39792   319.22894   789.1

[[553.38403  107.58351  800.       302.1496  ]
 [312.83493  385.17703  586.5634   664.47687 ]
 [521.27435  197.1049   800.       384.56863 ]
 [403.25528  457.45898  800.       800.      ]
 [  0.       346.92944  317.57812  800.      ]
 [399.51886  561.7682   800.       800.      ]
 [529.9336   456.9113   800.       800.      ]
 [745.34985  742.61346  800.       800.      ]
 [  0.       484.43652  561.2926   800.      ]
 [629.5232   190.61032  800.       518.33636 ]
 [285.2475     0.       800.       286.58496 ]
 [458.66104    0.       757.00824  156.95406 ]
 [447.05054  105.40502  800.       286.1372  ]
 [586.6788    81.189476 800.       479.77005 ]
 [398.92203  352.6855   726.6993   800.      ]
 [ 76.02496  190.62395  576.8188   374.66684 ]
 [411.95364  252.3398   800.       579.86176 ]
 [461.0217   324.73288  786.81146  800.      ]
 [315.697    405.7996   800.       738.99963 ]
 [626.4438    11.680698 800.       351.51987 ]
 [146.65604   84.97325  659.77106  293.46637 ]
 [449.83817  

[[5.53037231e+02 1.08911201e+02 8.00000000e+02 3.04506317e+02]
 [3.09363953e+02 3.86489105e+02 5.94437012e+02 6.67806458e+02]
 [5.17861389e+02 1.98518845e+02 8.00000000e+02 3.84528748e+02]
 [6.30859192e+02 1.93541885e+02 8.00000000e+02 5.13580811e+02]
 [4.02338409e+02 4.58791260e+02 8.00000000e+02 8.00000000e+02]
 [3.91738770e+02 5.66676331e+02 8.00000000e+02 8.00000000e+02]
 [0.00000000e+00 3.47572449e+02 3.16458557e+02 8.00000000e+02]
 [5.35966614e+02 4.56006012e+02 8.00000000e+02 8.00000000e+02]
 [8.74026337e+01 1.92837677e+02 5.75593201e+02 3.77887665e+02]
 [2.84841858e+02 0.00000000e+00 8.00000000e+02 2.87018768e+02]
 [5.89552856e+02 8.04327011e+01 8.00000000e+02 4.81556122e+02]
 [0.00000000e+00 4.81948090e+02 5.62137817e+02 8.00000000e+02]
 [4.52897736e+02 5.06587158e+02 8.00000000e+02 7.02338745e+02]
 [4.51266968e+02 1.07247902e+02 8.00000000e+02 2.87452637e+02]
 [5.70563049e+02 3.59692657e+02 8.00000000e+02 6.99262024e+02]
 [4.65110413e+02 3.24649963e+02 7.90747070e+02 8.000000

[[554.0994    105.593315  800.        304.72812  ]
 [517.0582    197.18892   800.        382.57474  ]
 [629.98645   189.56285   800.        516.2363   ]
 [  0.        329.67798   331.1164    800.       ]
 [272.14365     0.        800.        287.9738   ]
 [591.63916   428.1511    800.        800.       ]
 [589.66724    79.30289   800.        480.90015  ]
 [390.29443   562.15137   800.        800.       ]
 [458.5126    102.92468   800.        283.60016  ]
 [473.12128   476.8619    800.        800.       ]
 [ 91.16514   190.6867    588.17395   375.42133  ]
 [  0.        590.91547   333.10947   800.       ]
 [465.0315    300.09238   800.        800.       ]
 [629.3865     11.735153  800.        350.41498  ]
 [424.72644   248.37112   800.        580.2269   ]
 [459.69952   507.02914   800.        705.44055  ]
 [571.46313   356.99582   800.        694.67413  ]
 [339.32693   405.68152   800.        759.1135   ]
 [  0.        491.84164   576.8099    800.       ]
 [  0.          0.        415.6

[[556.0676   104.40176  800.       301.5949  ]
 [513.22986  197.50162  800.       383.00787 ]
 [275.14893    0.       800.       288.2644  ]
 [  0.       332.20404  324.28513  800.      ]
 [628.6437   188.76701  800.       515.2396  ]
 [315.7674   373.28986  596.64514  667.787   ]
 [389.2445   563.4111   800.       800.      ]
 [465.65796  300.5525   800.       800.      ]
 [592.15045  422.8018   800.       800.      ]
 [589.1757    79.407    800.       481.03848 ]
 [398.27548  454.1893   800.       800.      ]
 [  0.       489.34445  571.4873   800.      ]
 [450.29974  506.5033   800.       702.7914  ]
 [ 44.38591  675.65485  561.65344  800.      ]
 [116.772804 618.579    491.20142  800.      ]
 [420.3477   248.83083  800.       577.6352  ]
 [560.5269   601.25696  800.       800.      ]
 [563.1219   361.89844  800.       699.60864 ]
 [452.4488   101.659454 800.       281.41473 ]
 [  0.       586.7235   328.49643  800.      ]
 [393.26215  309.76172  730.9171   800.      ]
 [184.055    

[[550.81757  104.8695   800.       304.54813 ]
 [  0.       331.7127   327.27405  800.      ]
 [592.58936  426.7679   800.       800.      ]
 [513.4783   198.04044  800.       383.3273  ]
 [270.97562    0.       800.       289.298   ]
 [390.81848  562.26483  800.       800.      ]
 [631.2172   188.11356  800.       517.85443 ]
 [397.33694  449.81564  800.       800.      ]
 [591.25836   75.94159  800.       481.53668 ]
 [467.2063   295.4258   800.       800.      ]
 [421.723    245.69507  800.       579.8254  ]
 [  0.       590.0898   330.94955  800.      ]
 [  0.       489.83813  573.26935  800.      ]
 [453.62402  102.47977  800.       284.7842  ]
 [628.5945    11.342823 800.       353.40396 ]
 [452.6546   507.95935  800.       703.94696 ]
 [391.63733  297.58972  734.4491   800.      ]
 [195.17453  463.3427   742.78357  800.      ]
 [342.63736  406.30035  800.       758.93066 ]
 [116.23975  622.28345  497.88922  800.      ]
 [ 85.19795  190.17836  587.3622   370.5089  ]
 [  0.       

[[554.36176   104.116714  800.        304.46295  ]
 [  0.        330.73654   330.5479    800.       ]
 [514.4891    198.54242   800.        383.9758   ]
 [273.89185     0.        800.        289.34155  ]
 [591.1325    427.83392   800.        800.       ]
 [388.69492   562.22974   800.        800.       ]
 [630.5195    191.39717   800.        520.2004   ]
 [393.1016    447.77817   800.        800.       ]
 [422.04202   244.93518   800.        580.4548   ]
 [588.94385    76.419     800.        477.44208  ]
 [466.78247   296.4822    800.        800.       ]
 [  0.        592.4806    337.2374    800.       ]
 [342.8004    407.61795   800.        759.60846  ]
 [445.62317   102.86093   800.        283.8351   ]
 [630.8282     12.761248  800.        353.08942  ]
 [389.7317    294.47726   735.7626    800.       ]
 [  0.        490.17993   580.1259    800.       ]
 [ 72.71619   191.59473   586.77814   374.25702  ]
 [193.60568   461.3944    744.9132    800.       ]
 [187.54155     0.        632.1

[[561.02747   104.27062   800.        302.9741   ]
 [516.9771    198.07108   800.        382.83664  ]
 [271.11014     0.        800.        289.38327  ]
 [  0.        327.34576   331.89716   800.       ]
 [630.51404   189.2293    800.        516.9562   ]
 [591.30786   425.96912   800.        800.       ]
 [590.076      78.484955  800.        478.22986  ]
 [389.84674   562.6623    800.        800.       ]
 [447.57605   104.439095  800.        283.40146  ]
 [393.4872    449.41675   800.        800.       ]
 [  0.        591.7353    338.34625   800.       ]
 [467.70706   294.49405   800.        800.       ]
 [424.2669    246.56467   800.        578.43396  ]
 [630.8546     11.871302  800.        351.01575  ]
 [342.30026   406.43698   800.        757.77185  ]
 [450.82416   508.4884    800.        703.4528   ]
 [  0.        491.9753    578.8006    800.       ]
 [455.10034     0.        754.45184   155.09401  ]
 [453.81775   153.82173   800.        656.1135   ]
 [674.7156     43.90547   800. 

[[555.9935   107.23848  800.       304.41055 ]
 [628.2115   189.67242  800.       517.28925 ]
 [516.6043   198.17688  800.       383.60052 ]
 [271.709      0.       800.       289.44965 ]
 [  0.       323.78473  332.21973  800.      ]
 [590.9783   425.49847  800.       800.      ]
 [389.16718  562.5867   800.       800.      ]
 [593.8856    78.372406 800.       480.65616 ]
 [392.49905  449.0993   800.       800.      ]
 [426.39807  245.16534  800.       579.7034  ]
 [467.81955  291.7321   800.       800.      ]
 [448.4878   105.26645  800.       286.52905 ]
 [627.56274    9.575855 800.       354.72827 ]
 [343.273    407.24722  800.       760.33606 ]
 [  0.       488.87854  578.96387  800.      ]
 [  0.       589.6461   334.17807  800.      ]
 [676.57526   43.43817  800.       464.48907 ]
 [453.21655  508.85736  800.       702.6803  ]
 [186.82616    0.       631.4166   536.84174 ]
 [566.95703  358.33987  800.       696.30725 ]
 [386.07477  296.7063   735.27795  800.      ]
 [  0.       

[[553.76447  107.15188  800.       302.1943  ]
 [511.8313   198.69818  800.       384.07217 ]
 [271.8613     0.       800.       287.25873 ]
 [  0.       324.31052  326.86273  800.      ]
 [628.32227  187.86423  800.       516.30383 ]
 [591.8521   425.0223   800.       800.      ]
 [467.29315  296.57376  800.       800.      ]
 [446.96933  104.211136 800.       279.85507 ]
 [592.4775    78.167    800.       477.4447  ]
 [385.67957  563.80475  800.       800.      ]
 [315.79846  374.58328  595.72955  673.9006  ]
 [  0.       488.162    574.78186  800.      ]
 [ 84.15723  190.08716  585.79156  370.4902  ]
 [395.32477  453.49512  800.       800.      ]
 [631.0482    11.971676 800.       353.36618 ]
 [421.42648  248.23889  800.       577.71075 ]
 [451.27777    0.       753.80457  155.50316 ]
 [338.0156   407.42035  800.       755.75037 ]
 [452.97565  508.13058  800.       703.63605 ]
 [  0.         0.       138.0566   554.6707  ]
 [  0.         0.       410.78677  366.24637 ]
 [675.0897   

[[552.64923  104.509995 800.       303.68918 ]
 [509.1188   198.92363  800.       383.2879  ]
 [313.88306  372.1851   595.8016   673.92706 ]
 [629.2236   186.1858   800.       517.12085 ]
 [  0.       329.83322  322.86682  800.      ]
 [276.37442    0.       800.       285.64444 ]
 [592.98737  423.8492   800.       800.      ]
 [465.28497  302.65817  800.       800.      ]
 [593.2385    77.19388  800.       479.96463 ]
 [ 78.83797  190.84982  587.94543  373.16202 ]
 [388.04263  563.9364   800.       800.      ]
 [398.50208  454.52356  800.       800.      ]
 [445.07922  102.86299  800.       283.24628 ]
 [  0.       487.58713  572.4834   800.      ]
 [631.751     12.61692  800.       351.94717 ]
 [418.5648   251.05463  800.       578.10693 ]
 [392.7292   317.09256  731.1569   800.      ]
 [456.23322  506.67172  800.       704.67236 ]
 [330.49692  405.64966  800.       750.57697 ]
 [567.42676  359.7877   800.       696.28485 ]
 [  0.       592.83307  333.70743  800.      ]
 [673.8829   

[[552.43243   104.73188   800.        302.0041   ]
 [514.7736    198.91905   800.        381.64438  ]
 [315.13602   373.56506   593.3274    676.7383   ]
 [  0.        332.66135   320.80188   800.       ]
 [275.7291      0.        800.        285.34686  ]
 [464.59335   303.77338   799.3707    800.       ]
 [628.3921    186.67732   800.        516.7329   ]
 [  0.        486.42435   567.81586   800.       ]
 [592.6159    425.83624   800.        800.       ]
 [586.05347    79.76917   800.        479.13785  ]
 [445.79248   104.83343   800.        283.99176  ]
 [388.84772   562.4013    800.        800.       ]
 [398.59888   453.5675    800.        800.       ]
 [ 83.43608   187.66313   583.416     373.57642  ]
 [418.21765   250.37308   800.        577.51514  ]
 [630.5543     12.418163  800.        351.87973  ]
 [454.52396   507.94278   800.        704.3628   ]
 [255.95412   334.10733   659.7526    800.       ]
 [452.9687      0.        756.3775    156.39912  ]
 [395.9392    327.34937   731.4

[[554.4114    103.55509   800.        303.9332   ]
 [319.39926   377.0323    587.09357   670.7625   ]
 [629.0325    188.02814   800.        512.08466  ]
 [516.3691    197.13426   800.        380.37457  ]
 [587.04504    78.392555  800.        479.92435  ]
 [  0.        346.96054   312.61697   800.       ]
 [ 85.558174  191.59566   579.9457    372.45535  ]
 [287.4425      0.        800.        284.50208  ]
 [  0.        482.1696    559.3738    800.       ]
 [449.0403    101.51298   800.        281.41077  ]
 [464.98447   324.77893   793.2372    800.       ]
 [449.44553   507.97354   800.        704.10736  ]
 [  0.        590.46814   347.24954   800.       ]
 [407.71356   459.5973    800.        800.       ]
 [417.32855   256.66318   800.        577.57996  ]
 [631.6756     11.235714  800.        348.50797  ]
 [397.45905   565.9265    800.        800.       ]
 [594.03235   431.13824   800.        800.       ]
 [563.9523    361.99857   800.        700.31146  ]
 [602.20306   286.4743    800. 

[[552.20306  104.542305 800.       304.33374 ]
 [316.63345  375.6783   590.5266   668.41266 ]
 [516.90765  197.69199  800.       382.39044 ]
 [628.15674  187.567    800.       514.7718  ]
 [ 79.49414  193.76555  581.008    374.28125 ]
 [594.72455   77.275154 800.       483.66565 ]
 [452.32205  103.849884 800.       284.4211  ]
 [451.4033   508.10046  800.       705.06104 ]
 [368.70657  389.08163  703.08514  695.84686 ]
 [  0.       359.48218  306.45886  800.      ]
 [409.69113  460.7564   800.       800.      ]
 [411.62033  258.7911   800.       579.8695  ]
 [563.33093  359.17142  800.       700.1479  ]
 [294.5587     0.       800.       284.7856  ]
 [  0.       595.1997   339.1862   800.      ]
 [399.35898  564.10156  800.       800.      ]
 [596.42053  434.2677   800.       800.      ]
 [  0.       481.38116  556.1974   800.      ]
 [ 54.991577 276.72015  621.59796  451.47025 ]
 [631.3933    11.602378 800.       359.3254  ]
 [409.39905  365.59747  724.6207   800.      ]
 [601.3662   

[[313.6426    374.70804   590.6456    673.26245  ]
 [551.5724    105.85941   800.        304.33807  ]
 [  0.        349.78326   311.60333   800.       ]
 [629.188     189.13391   800.        513.71155  ]
 [521.67676   197.5317    800.        382.2086   ]
 [  0.        591.538     337.98175   800.       ]
 [411.4264    254.6588    800.        582.01636  ]
 [ 90.14197   191.97092   576.6742    367.82227  ]
 [293.04047     0.        800.        285.83817  ]
 [395.3635    561.14514   800.        800.       ]
 [596.31793   428.82462   800.        800.       ]
 [  0.        484.0255    559.71625   800.       ]
 [455.1836    163.45074   800.        662.34924  ]
 [399.43845   462.05283   800.        800.       ]
 [323.8379    405.6189    800.        742.07855  ]
 [561.774     357.52396   800.        700.47437  ]
 [446.0473    100.70443   800.        285.2252   ]
 [454.97113   508.68616   800.        704.5566   ]
 [462.0041    327.1976    793.2336    800.       ]
 [591.7651     81.53877   800. 

[[555.70105  103.98301  800.       306.2378  ]
 [521.6831   196.95195  800.       382.34412 ]
 [626.7881   188.976    800.       513.91376 ]
 [312.25415  377.67172  592.2902   668.688   ]
 [405.33878  257.0059   800.       579.6563  ]
 [ 89.02635  191.2136   587.4578   371.85736 ]
 [  0.       360.21432  311.35034  800.      ]
 [404.83847  462.8662   800.       800.      ]
 [399.67328  564.5964   800.       800.      ]
 [310.6109   403.07523  800.       737.069   ]
 [596.5475   435.26764  800.       800.      ]
 [530.8121   394.39474  800.       642.8993  ]
 [460.94446  507.3533   800.       705.1505  ]
 [448.46454  161.77673  800.       663.66595 ]
 [295.05344    0.       800.       287.83884 ]
 [591.9986    82.82657  800.       483.92557 ]
 [407.39697  364.47302  721.56055  800.      ]
 [443.1931   101.419876 800.       284.18127 ]
 [  0.       480.96237  558.0556   800.      ]
 [  0.       593.94604  332.06955  800.      ]
 [452.49585    0.       757.4059   153.66351 ]
 [141.16824  

[[554.1037   103.22726  800.       306.04785 ]
 [310.21637  371.66318  595.46124  668.2355  ]
 [  0.       349.68887  315.883    800.      ]
 [515.9747   197.05595  800.       381.33215 ]
 [624.80255  187.93034  800.       513.3037  ]
 [288.63846    0.       800.       286.4864  ]
 [413.18048  255.59387  800.       578.87585 ]
 [  0.        69.97621  271.66165  695.7216  ]
 [403.17822  461.6222   800.       800.      ]
 [  0.       592.48535  329.0289   800.      ]
 [  0.       486.26605  561.3209   800.      ]
 [394.51855  565.5138   800.       800.      ]
 [320.1785   403.10068  800.       738.8914  ]
 [ 78.49307  195.71579  591.27905  373.3648  ]
 [534.9536   457.94925  800.       800.      ]
 [  0.         0.       312.4291   273.86475 ]
 [447.60715  101.59808  800.       281.9012  ]
 [  0.         0.       400.3001   360.00323 ]
 [452.6965   160.69022  800.       658.6229  ]
 [463.77274  322.81326  789.9503   800.      ]
 [451.0047   506.07437  800.       703.80646 ]
 [560.3584   

[[550.7675   103.36622  800.       305.38293 ]
 [308.35596  370.4723   593.36676  661.8055  ]
 [516.4125   196.27351  800.       381.33276 ]
 [449.28384  102.84087  800.       282.4826  ]
 [  0.       345.77438  316.1141   800.      ]
 [626.84827  187.71759  800.       513.2715  ]
 [285.43335    0.       800.       285.37534 ]
 [404.35825  460.1939   800.       800.      ]
 [412.67685  255.08481  800.       578.9391  ]
 [535.8983   458.68854  800.       800.      ]
 [394.65298  564.7471   800.       800.      ]
 [446.70175    0.       757.1527   153.04205 ]
 [ 79.34585  192.7516   584.9916   373.27167 ]
 [  0.       484.60797  560.4718   800.      ]
 [589.34973   80.20346  800.       480.7785  ]
 [323.79572  402.09427  800.       740.2062  ]
 [  0.        62.167213 268.3223   701.24316 ]
 [  0.       592.67035  331.97382  800.      ]
 [632.85126   12.5633   800.       357.23947 ]
 [464.1089   322.01016  791.2683   800.      ]
 [405.53732  346.944    725.15094  800.      ]
 [450.76135  

[[555.8961   103.050804 800.       302.91205 ]
 [279.58588    0.       800.       285.3163  ]
 [  0.         0.       320.27963  273.9296  ]
 [  0.       339.17993  319.6078   800.      ]
 [  0.        76.551315 272.70416  684.5181  ]
 [524.74115  195.70844  800.       382.0963  ]
 [303.4954   378.89075  598.3345   665.52185 ]
 [466.8106   310.09537  794.6162   800.      ]
 [626.1681   188.85042  800.       514.6446  ]
 [532.02545  456.56348  800.       800.      ]
 [454.00372  101.89873  800.       283.64243 ]
 [415.60858  251.58127  800.       578.3634  ]
 [398.46707  457.30157  800.       800.      ]
 [390.3269   564.3377   800.       800.      ]
 [587.2708    82.71755  800.       482.1056  ]
 [  0.         0.       167.05212  581.6449  ]
 [327.81567  405.4699   800.       745.0129  ]
 [  0.       490.04034  567.1876   800.      ]
 [ 72.589424 192.49843  595.5702   372.3395  ]
 [ 50.884293  69.05086  528.03925  301.802   ]
 [  0.         0.       402.27753  358.8997  ]
 [453.08032  

[[559.2127   105.74193  800.       301.8754  ]
 [310.27368  379.98096  596.3202   671.06946 ]
 [519.47363  196.64139  800.       382.64624 ]
 [  0.       340.73688  318.64114  800.      ]
 [465.9647   309.57974  795.9284   800.      ]
 [ 85.17952  190.82933  595.80005  372.6888  ]
 [281.55765    0.       800.       286.5828  ]
 [628.5442   191.08585  800.       516.42365 ]
 [534.0204   458.64078  800.       800.      ]
 [389.28424  564.10144  800.       800.      ]
 [399.72278  457.59314  800.       800.      ]
 [449.25046  106.59058  800.       281.61835 ]
 [415.46048  250.31451  800.       578.6957  ]
 [327.13638  405.43707  800.       745.4722  ]
 [  0.       490.19366  566.498    800.      ]
 [  0.        76.08242  267.1308   684.4955  ]
 [592.9678    82.98578  800.       483.05157 ]
 [630.07385   11.108637 800.       353.55286 ]
 [454.9252   157.23975  800.       659.4778  ]
 [447.9665   505.47086  800.       707.04175 ]
 [563.7776   355.29556  800.       697.001   ]
 [398.5699   

[[550.0056    107.22998   800.        303.66077  ]
 [283.41736     0.        800.        285.62555  ]
 [  0.        338.31015   317.70056   800.       ]
 [307.73282   378.0381    596.6016    666.2946   ]
 [519.8583    196.63966   800.        384.72458  ]
 [ 81.11765   192.21205   580.1425    375.04553  ]
 [472.30798   306.51138   798.2444    800.       ]
 [  0.        483.90573   568.05676   800.       ]
 [532.4501    457.62823   800.        800.       ]
 [628.7257    187.0744    800.        518.0257   ]
 [390.0432    566.5329    800.        800.       ]
 [451.60904   104.29158   800.        284.6502   ]
 [327.60175   406.64792   800.        744.07745  ]
 [418.92706   249.60127   800.        579.422    ]
 [397.83255   460.43243   800.        800.       ]
 [  0.        594.0134    343.74548   800.       ]
 [628.074      12.007225  800.        353.90805  ]
 [454.57422   156.8406    800.        659.28467  ]
 [448.6065    506.74353   800.        705.6054   ]
 [591.0343     79.12185   800. 

[[553.62366   102.48867   800.        305.90955  ]
 [305.7474    375.99747   596.0209    664.2895   ]
 [527.4975    196.83983   800.        382.8335   ]
 [  0.        337.41135   322.57376   800.       ]
 [279.57065     0.        800.        286.37076  ]
 [  0.         67.349556  270.88995   692.81256  ]
 [628.36487   190.68033   800.        516.0919   ]
 [468.42755   311.0594    795.0778    800.       ]
 [452.79318   103.1656    800.        284.98132  ]
 [532.6545    457.94858   800.        800.       ]
 [419.40118   250.10144   800.        578.74115  ]
 [  0.          0.        318.28693   273.83887  ]
 [329.2504    405.01648   800.        746.57605  ]
 [390.72864   565.60675   800.        800.       ]
 [397.89096   458.4241    800.        800.       ]
 [  0.        488.94177   566.0922    800.       ]
 [ 61.396408  191.75208   599.2394    375.23972  ]
 [  0.          0.        164.52754   575.40326  ]
 [454.64746   157.31654   800.        657.37006  ]
 [590.2067     80.289314  800. 

[[551.4977   103.86764  800.       304.35547 ]
 [276.72556    0.       800.       287.45483 ]
 [305.04068  375.94504  598.12134  675.20355 ]
 [515.9858   197.32874  800.       382.5511  ]
 [469.51483  295.9392   800.       800.      ]
 [  0.       324.55374  328.308    800.      ]
 [  0.        67.54017  270.98618  690.20325 ]
 [  0.         0.       317.76038  275.93573 ]
 [386.1576   563.1218   800.       800.      ]
 [631.5193   191.01192  800.       515.08307 ]
 [591.4853   417.04916  800.       800.      ]
 [  0.         0.       166.204    578.22314 ]
 [394.44595  454.96393  800.       800.      ]
 [421.7527   247.71819  800.       577.6327  ]
 [  0.       487.11172  567.41016  800.      ]
 [341.07623  406.43372  800.       750.497   ]
 [447.24377  102.84267  800.       282.06647 ]
 [589.4709    78.82104  800.       482.84317 ]
 [  0.         0.       403.5821   363.7014  ]
 [  0.        36.723473 287.6832   508.3864  ]
 [  0.       365.93024  373.64456  800.      ]
 [244.49368  

[[548.87427   104.10714   800.        303.66534  ]
 [296.2136    368.94455   602.2476    669.99225  ]
 [274.89725     0.        800.        287.62946  ]
 [515.5018    196.4725    800.        382.31787  ]
 [468.88074   293.13608   800.        800.       ]
 [630.21967   188.83131   800.        512.65955  ]
 [  0.        321.87112   326.8521    800.       ]
 [450.43173   103.48757   800.        283.1271   ]
 [589.8909     76.15221   800.        485.77222  ]
 [591.9149    417.08975   800.        800.       ]
 [387.46085   563.26215   800.        800.       ]
 [  0.        485.0659    570.10754   800.       ]
 [396.34546   455.98108   800.        800.       ]
 [451.5824      0.        755.5105    161.61763  ]
 [344.37772   405.32837   800.        749.8488   ]
 [422.92657   246.82544   800.        576.93463  ]
 [630.8745      9.3015785 800.        354.0841   ]
 [  0.        594.03394   349.20325   800.       ]
 [  0.          0.        408.53915   363.12106  ]
 [244.53537   326.8307    656.2

[[548.64435  103.17322  800.       304.84415 ]
 [  0.       320.16516  321.6046   800.      ]
 [402.21277  455.46686  800.       800.      ]
 [ 77.69711  192.05031  583.27704  377.28244 ]
 [  0.       480.45813  559.18665  800.      ]
 [278.77618    0.       800.       290.79773 ]
 [391.80765  566.10706  800.       800.      ]
 [622.95     189.52638  800.       508.8896  ]
 [517.80383  196.6184   800.       384.11066 ]
 [460.45184  300.93463  789.66614  800.      ]
 [592.421    421.5666   800.       800.      ]
 [587.0971    75.80965  800.       485.22482 ]
 [446.8261   103.19295  800.       288.92307 ]
 [346.32028  392.91623  800.       747.486   ]
 [415.0594   257.46017  800.       572.17944 ]
 [245.49026  332.84457  667.14685  800.      ]
 [  0.       593.9903   333.327    800.      ]
 [629.0967     8.858228 800.       354.67343 ]
 [297.2769   363.65778  597.67883  672.3163  ]
 [526.1727   388.17502  800.       644.2656  ]
 [401.15057  339.36624  739.834    800.      ]
 [  0.       

[[550.9052   105.10057  800.       306.2373  ]
 [  0.       313.12057  325.9987   800.      ]
 [402.48718  454.9427   800.       800.      ]
 [273.69794    0.       800.       291.9352  ]
 [ 64.89086  189.24315  570.6005   378.72217 ]
 [622.31714  192.54419  800.       507.83075 ]
 [  0.       482.23877  560.535    800.      ]
 [517.70074  195.24553  800.       381.7084  ]
 [390.484    565.17377  800.       800.      ]
 [458.17957  291.4365   787.0589   800.      ]
 [591.26355  420.152    800.       800.      ]
 [587.50073   78.97305  800.       483.2973  ]
 [350.4552   388.94525  800.       750.5745  ]
 [526.8857   387.5614   800.       643.213   ]
 [242.68948  324.08435  670.6789   800.      ]
 [409.3256   259.5515   800.       567.5246  ]
 [  0.       593.4178   330.01395  800.      ]
 [  0.       370.62424  363.98868  800.      ]
 [  0.         0.       413.76794  357.69705 ]
 [449.6792    98.112854 800.       287.99075 ]
 [628.5625    11.671484 800.       352.47168 ]
 [  0.       

[[551.1744    106.208206  800.        305.522    ]
 [  0.        317.92      323.1037    800.       ]
 [402.92276   455.8013    800.        800.       ]
 [  0.        483.1234    559.4633    800.       ]
 [275.10974     0.        800.        291.48694  ]
 [623.49744   191.28128   800.        506.85196  ]
 [459.2944    291.60306   786.0574    800.       ]
 [590.69214   424.5858    800.        800.       ]
 [390.8183    566.46967   800.        800.       ]
 [513.265     196.91656   800.        383.97073  ]
 [243.54387   330.46463   671.53394   800.       ]
 [ 66.66122   187.9241    572.90814   380.8639   ]
 [345.80652   389.5074    800.        749.0635   ]
 [410.22357   261.30634   800.        567.5733   ]
 [  0.        366.69415   359.50232   800.       ]
 [584.7445     77.87654   800.        487.3992   ]
 [399.94016   334.82224   743.3719    800.       ]
 [  0.          0.        269.25687   559.5783   ]
 [  0.        591.3287    337.24518   800.       ]
 [  0.          0.        412.4

[[5.47665283e+02 1.06937553e+02 8.00000000e+02 3.03263245e+02]
 [2.74387970e+02 0.00000000e+00 8.00000000e+02 2.90873444e+02]
 [0.00000000e+00 3.14146423e+02 3.27216400e+02 8.00000000e+02]
 [5.11801636e+02 1.97328003e+02 8.00000000e+02 3.81620636e+02]
 [3.99688110e+02 4.52368347e+02 8.00000000e+02 8.00000000e+02]
 [4.59969421e+02 2.86737396e+02 7.95622803e+02 8.00000000e+02]
 [6.25055115e+02 1.85228043e+02 8.00000000e+02 5.10620972e+02]
 [5.90132751e+02 4.14954956e+02 8.00000000e+02 8.00000000e+02]
 [3.90250244e+02 5.64545044e+02 8.00000000e+02 8.00000000e+02]
 [6.70384140e+01 1.89668793e+02 5.85278503e+02 3.77111389e+02]
 [2.41232483e+02 3.31490845e+02 6.66044983e+02 8.00000000e+02]
 [4.40886200e+02 9.97347031e+01 8.00000000e+02 2.88194946e+02]
 [5.89391174e+02 8.24674835e+01 8.00000000e+02 4.90838043e+02]
 [0.00000000e+00 4.84002930e+02 5.67706360e+02 8.00000000e+02]
 [3.59730469e+02 3.95253021e+02 8.00000000e+02 7.55060181e+02]
 [6.26540588e+02 1.07091188e+01 8.00000000e+02 3.541304

[[549.4215    105.75108   800.        302.74344  ]
 [  0.        325.505     319.03693   800.       ]
 [  0.        478.56326   554.78784   800.       ]
 [242.56439   338.13553   654.7333    800.       ]
 [280.11243     0.        800.        285.9526   ]
 [508.175     198.08832   800.        381.915    ]
 [624.487     188.49762   800.        509.16614  ]
 [468.72006   294.81284   793.77454   800.       ]
 [  0.        370.47058   370.5995    800.       ]
 [403.35983   456.98642   800.        800.       ]
 [390.2731    563.8355    800.        800.       ]
 [ 59.428978  188.27887   586.2024    378.6149   ]
 [586.5331     79.99115   800.        487.89267  ]
 [  0.        592.27155   331.312     800.       ]
 [442.57202   102.399704  800.        286.65723  ]
 [590.5784    414.6999    800.        800.       ]
 [300.75195   360.45242   610.6361    681.70013  ]
 [628.5319      7.9493403 800.        348.56256  ]
 [ 80.39888   412.45938   382.8146    800.       ]
 [  0.          0.        409.0

[[547.93665  105.24069  800.       305.3188  ]
 [  0.       336.70074  315.66782  800.      ]
 [  0.       478.94717  547.54846  800.      ]
 [ 60.261322 193.41206  580.6552   376.3171  ]
 [  0.       368.13632  372.83328  800.      ]
 [405.4143   459.78357  800.       800.      ]
 [245.73853  343.6248   646.7075   800.      ]
 [391.0191   564.3431   800.       800.      ]
 [471.01074  303.94995  792.0957   800.      ]
 [623.26306  185.14778  800.       509.208   ]
 [283.49335    0.       800.       285.1792  ]
 [  0.       595.20483  336.94748  800.      ]
 [  0.        65.39135  268.7694   691.98834 ]
 [510.40945  197.43475  800.       381.45193 ]
 [529.954    446.96857  800.       800.      ]
 [591.6371    83.05711  800.       488.1518  ]
 [  0.         0.       313.754    279.228   ]
 [352.51044  396.4252   800.       742.9361  ]
 [440.94934  102.73819  800.       287.31335 ]
 [417.9845   259.48157  800.       572.79553 ]
 [  0.         0.       401.17807  359.7599  ]
 [ 81.305504 

[[552.9767   104.90767  800.       302.17157 ]
 [  0.       337.29892  315.00574  800.      ]
 [  0.       476.4067   549.54254  800.      ]
 [ 65.030525 191.8816   579.78644  380.48138 ]
 [  0.       367.0271   363.8426   800.      ]
 [244.55215  348.50104  655.66     800.      ]
 [281.94852    0.       800.       286.34332 ]
 [408.18262  461.24667  800.       800.      ]
 [398.94928  566.4676   800.       800.      ]
 [624.69104  187.8757   800.       507.93756 ]
 [472.75525  304.22708  788.9043   800.      ]
 [510.3023   196.00702  800.       384.1271  ]
 [345.27072  394.2547   800.       739.65137 ]
 [593.584     79.23253  800.       488.94644 ]
 [532.4327   444.8343   800.       800.      ]
 [415.49615  258.06107  800.       571.6125  ]
 [523.3373   391.31952  800.       638.79755 ]
 [  0.       592.2363   338.88306  800.      ]
 [442.99384  506.0339   800.       702.08624 ]
 [ 79.58826  426.1465   384.18097  800.      ]
 [624.64435    8.010483 800.       352.2851  ]
 [  0.       

[[548.66974   106.92682   800.        303.70956  ]
 [ 65.79592   191.8981    568.98224   377.9196   ]
 [  0.        332.8129    311.86237   800.       ]
 [  0.        476.46747   553.3625    800.       ]
 [509.0332    197.35692   800.        382.3356   ]
 [624.14734   188.11945   800.        508.41013  ]
 [408.00552   460.66208   800.        800.       ]
 [  0.        368.71066   365.05197   800.       ]
 [397.39676   566.9836    800.        800.       ]
 [590.51807    81.012436  800.        488.1495   ]
 [  0.        592.6218    332.6023    800.       ]
 [283.135       0.        800.        287.34686  ]
 [145.42973    90.48167   651.74133   287.8071   ]
 [530.1628    448.65283   800.        800.       ]
 [245.28351   339.51776   660.3358    800.       ]
 [441.68805   102.6901    800.        287.24664  ]
 [629.2725     11.285389  800.        351.85104  ]
 [448.55084     0.        751.9525    158.89969  ]
 [ 83.34906   427.8405    386.55728   800.       ]
 [470.3676    313.55066   787.2

[[5.52197998e+02 1.05481430e+02 8.00000000e+02 3.05159180e+02]
 [0.00000000e+00 3.23474182e+02 3.15544739e+02 8.00000000e+02]
 [4.02824493e+02 4.58647156e+02 8.00000000e+02 8.00000000e+02]
 [0.00000000e+00 4.74546906e+02 5.53800964e+02 8.00000000e+02]
 [7.22160110e+01 1.91997681e+02 5.81920898e+02 3.77410950e+02]
 [3.94661713e+02 5.65623108e+02 8.00000000e+02 8.00000000e+02]
 [6.22464478e+02 1.83963425e+02 8.00000000e+02 5.09160339e+02]
 [5.08005615e+02 1.97595032e+02 8.00000000e+02 3.82691803e+02]
 [5.25364929e+02 4.47365753e+02 8.00000000e+02 8.00000000e+02]
 [0.00000000e+00 5.95736633e+02 3.29887482e+02 8.00000000e+02]
 [0.00000000e+00 3.67096375e+02 3.59900787e+02 8.00000000e+02]
 [2.78024048e+02 0.00000000e+00 8.00000000e+02 2.89531372e+02]
 [6.26817322e+02 9.95736122e+00 8.00000000e+02 3.51759766e+02]
 [4.44734375e+02 9.98265381e+01 8.00000000e+02 2.88339722e+02]
 [5.84554199e+02 7.99333572e+01 8.00000000e+02 4.86929321e+02]
 [4.08450317e+02 7.35297089e+01 8.00000000e+02 4.045765

[[547.2385   105.85298  800.       303.0798  ]
 [  0.       334.56354  316.89227  800.      ]
 [ 69.01078  189.18047  582.23114  383.2499  ]
 [404.38852  459.90005  800.       800.      ]
 [624.8945   184.98477  800.       510.9248  ]
 [  0.       475.84982  556.30914  800.      ]
 [513.2617   196.97029  800.       383.759   ]
 [398.09674  566.4384   800.       800.      ]
 [  0.       366.00925  359.2579   800.      ]
 [524.88654  451.08585  800.       800.      ]
 [280.21677    0.       800.       290.51984 ]
 [587.15533   83.527084 800.       492.17377 ]
 [108.1511    99.14762  565.3794   271.738   ]
 [413.5116    71.70696  800.       404.1233  ]
 [330.50537  389.90335  800.       736.8006  ]
 [ 60.96332   67.748405 518.1476   317.07434 ]
 [455.8526     0.       753.2198   159.44833 ]
 [561.7344   599.53253  800.       800.      ]
 [ 22.188807 639.5584   384.07153  800.      ]
 [626.4815     5.120814 800.       353.80853 ]
 [449.27768  101.770164 800.       286.6265  ]
 [402.77814  

[[547.05707  104.45299  800.       304.74716 ]
 [  0.       330.04593  321.16275  800.      ]
 [403.76605  459.67236  800.       800.      ]
 [ 70.48573  188.23138  586.55884  377.625   ]
 [  0.       479.7125   559.0239   800.      ]
 [512.1992   197.57268  800.       383.44907 ]
 [622.9083   188.22525  800.       511.12415 ]
 [  0.       366.27493  362.82224  800.      ]
 [397.32306  566.8471   800.       800.      ]
 [526.26685  448.40878  800.       800.      ]
 [279.01093    0.       800.       291.80243 ]
 [  0.         0.       140.49478  537.77325 ]
 [ 99.627686  99.218346 572.4025   269.64218 ]
 [334.15262  390.59143  800.       740.89813 ]
 [583.66516   80.62191  800.       489.27325 ]
 [456.95935    0.       751.30853  158.04134 ]
 [  0.        89.49307  234.27928  287.2618  ]
 [  0.        57.21977  264.81274  695.5476  ]
 [  0.         0.       409.3946   356.0396  ]
 [532.62445  732.55133  606.4517   800.      ]
 [304.059    364.23444  599.441    663.44617 ]
 [466.79126  

[[556.8637   103.36943  800.       305.34302 ]
 [278.5195     0.       800.       291.68552 ]
 [393.88104  563.09454  800.       800.      ]
 [401.08157  456.4906   800.       800.      ]
 [ 75.47357  189.607    580.2538   379.40234 ]
 [591.56006  404.65268  800.       800.      ]
 [  0.       369.52466  365.6632   800.      ]
 [515.6623   196.88055  800.       380.48755 ]
 [622.8454   191.9197   800.       510.4253  ]
 [  0.       302.32022  336.38654  800.      ]
 [468.41177  276.03864  799.31213  800.      ]
 [362.07816  393.82077  800.       754.1811  ]
 [  0.       475.0327   566.1182   800.      ]
 [584.9362    78.647995 800.       486.09128 ]
 [ 64.54332   72.19937  519.56104  314.78784 ]
 [531.99646  732.99316  605.7179   800.      ]
 [229.38693  314.07434  676.6946   800.      ]
 [149.68738   87.731026 661.2978   289.354   ]
 [  0.         0.       412.65448  363.7382  ]
 [ 48.938225 679.4722   572.88824  800.      ]
 [  0.         0.       273.9753   559.4953  ]
 [415.08554  

[[551.7353   105.11241  800.       301.98373 ]
 [  0.       473.71063  562.8583   800.      ]
 [402.94266  460.3976   800.       800.      ]
 [396.17053  564.36365  800.       800.      ]
 [  0.       313.74243  326.37372  800.      ]
 [280.59622    0.       800.       290.52692 ]
 [ 78.33784  193.38145  573.04065  379.28046 ]
 [  0.       368.77176  364.10184  800.      ]
 [511.80457  196.49869  800.       381.07367 ]
 [523.6271   441.8911   800.       800.      ]
 [623.27014  189.04982  800.       510.5567  ]
 [445.65463  101.844666 800.       288.51447 ]
 [588.6315    81.993866 800.       485.11682 ]
 [470.6305   296.64264  792.7023   800.      ]
 [629.3342    10.763157 800.       352.62213 ]
 [344.59827  391.89682  800.       746.1128  ]
 [235.3647   330.6057   670.2609   800.      ]
 [304.97675  364.14615  604.8784   666.00415 ]
 [  0.         0.       407.78607  363.8948  ]
 [531.4485   732.02     604.3051   800.      ]
 [239.70578   83.00494  718.41266  301.0787  ]
 [458.81418  

[[552.62396  105.451294 800.       305.08896 ]
 [  0.       474.5665   555.87024  800.      ]
 [ 79.06999  196.32773  571.8749   377.32678 ]
 [  0.       322.90808  319.125    800.      ]
 [408.9414   461.61346  800.       800.      ]
 [398.07245  564.7115   800.       800.      ]
 [282.6397     0.       800.       290.53775 ]
 [  0.       369.41687  363.26724  800.      ]
 [512.98535  198.35495  800.       384.0744  ]
 [304.2812   360.83182  603.7941   659.9224  ]
 [526.10504  441.76892  800.       800.      ]
 [242.34917  332.40698  665.48804  800.      ]
 [468.80206  305.34085  788.82983  800.      ]
 [622.3829   188.06673  800.       511.41342 ]
 [ 87.13873  431.0664   386.98306  800.      ]
 [443.0316   102.41659  800.       290.12686 ]
 [523.05835  387.57288  800.       641.87744 ]
 [591.32      81.19199  800.       486.9795  ]
 [341.69193  392.25592  800.       742.33167 ]
 [405.43097  352.57346  732.5429   800.      ]
 [628.40765   13.512468 800.       351.501   ]
 [  0.       

[[555.49634  105.083176 800.       303.71838 ]
 [ 82.306984 190.84673  569.9219   378.26654 ]
 [514.25354  198.78645  800.       380.9845  ]
 [404.8751   460.21738  800.       800.      ]
 [  0.       343.50766  313.74146  800.      ]
 [443.93988  101.74573  800.       286.09064 ]
 [620.1938   185.1378   800.       515.55255 ]
 [398.01984  561.5862   800.       800.      ]
 [306.51364  369.95166  597.1497   659.7127  ]
 [  0.       475.30356  554.2872   800.      ]
 [408.74347  371.21786  726.29004  800.      ]
 [524.8278   447.77518  800.       800.      ]
 [ 97.152374 105.755875 569.17413  269.40442 ]
 [  0.       362.82     357.59393  800.      ]
 [526.71533  389.09525  800.       640.36334 ]
 [626.2252     6.97819  800.       350.90585 ]
 [587.5639    80.68666  800.       482.4373  ]
 [283.7177     0.       800.       291.2837  ]
 [ 88.103806 433.6894   385.42337  800.      ]
 [193.7612   468.9783   654.1069   800.      ]
 [449.08133  502.7732   800.       705.5735  ]
 [  0.       

[[553.66724  103.97836  800.       304.99454 ]
 [ 84.6195   191.60187  572.3562   379.21222 ]
 [513.8876   197.8313   800.       382.46146 ]
 [408.9053   463.0435   800.       800.      ]
 [399.75165  564.1317   800.       800.      ]
 [447.124    102.836624 800.       287.65497 ]
 [  0.       354.33417  308.99762  800.      ]
 [526.73004  387.55777  800.       641.17395 ]
 [151.84203   90.771614 666.58307  290.80075 ]
 [412.0497   384.43393  719.88605  800.      ]
 [529.228    459.78326  800.       800.      ]
 [  0.       592.05444  336.74225  800.      ]
 [624.9563   190.67805  800.       516.2301  ]
 [317.15408  371.89163  591.4358   656.54395 ]
 [ 79.64501  438.43933  393.20282  800.      ]
 [  0.       471.94055  550.24927  800.      ]
 [413.09952   71.085106 800.       405.72177 ]
 [450.49625  500.6719   800.       706.30176 ]
 [197.92163  478.37354  653.9791   800.      ]
 [457.69925    0.       753.1652   158.10286 ]
 [  0.       360.41095  365.21262  800.      ]
 [558.6462   

[[555.3264   103.712105 800.       304.0316  ]
 [516.90533  198.55511  800.       378.43567 ]
 [406.14996  461.1793   800.       800.      ]
 [397.46658  563.8422   800.       800.      ]
 [  0.       343.06778  315.37286  800.      ]
 [ 79.152176 190.84985  566.9884   377.0684  ]
 [524.1557   386.69003  800.       641.1614  ]
 [443.94928  100.49949  800.       287.10593 ]
 [408.17136  367.6006   724.4615   800.      ]
 [526.39667  455.75027  800.       800.      ]
 [ 94.478134 103.80607  567.0873   270.6341  ]
 [  0.       478.15668  550.87756  800.      ]
 [315.52133  365.98953  590.8493   655.04596 ]
 [625.68445  186.66008  800.       514.1181  ]
 [459.42578  500.09238  800.       707.6234  ]
 [587.9117    81.69744  800.       485.00128 ]
 [163.94458   86.555305 658.5625   294.62833 ]
 [412.87375   73.75381  800.       404.40244 ]
 [452.4249     0.       755.1731   155.09746 ]
 [284.67413    0.       800.       291.71545 ]
 [630.8275    13.582945 800.       354.1008  ]
 [  0.       

[[557.47754   104.70034   800.        302.85052  ]
 [ 79.55515   189.17587   577.3909    378.036    ]
 [  0.        472.18365   551.5131    800.       ]
 [  0.        338.94272   314.20636   800.       ]
 [406.04138   461.58484   800.        800.       ]
 [513.5709    197.91704   800.        378.17487  ]
 [447.78952    98.75153   800.        286.30267  ]
 [395.2904    564.8988    800.        800.       ]
 [161.44385    86.98563   656.8611    292.5794   ]
 [246.03564   334.8817    668.3119    800.       ]
 [596.01135   415.77502   800.        800.       ]
 [280.59103     0.        800.        292.12357  ]
 [523.2089    385.9435    800.        641.6499   ]
 [411.93066   364.289     728.4514    800.       ]
 [413.0498     72.44389   800.        406.00186  ]
 [359.05313   311.08908   537.63153   646.2007   ]
 [463.1613    310.08176   782.8093    800.       ]
 [457.87115     0.        754.9489    157.61478  ]
 [  0.        592.0231    339.91562   800.       ]
 [344.03906   388.90866   800. 

[[5.53802490e+02 1.05205322e+02 8.00000000e+02 3.03593597e+02]
 [0.00000000e+00 3.39360596e+02 3.15429932e+02 8.00000000e+02]
 [0.00000000e+00 4.70866211e+02 5.47858337e+02 8.00000000e+02]
 [7.72250214e+01 1.92598221e+02 5.77646912e+02 3.80164795e+02]
 [4.07413422e+02 4.62005615e+02 8.00000000e+02 8.00000000e+02]
 [4.46032898e+02 1.01905609e+02 8.00000000e+02 2.87131500e+02]
 [5.14184021e+02 1.98791229e+02 8.00000000e+02 3.80524017e+02]
 [4.00457397e+02 5.65820801e+02 8.00000000e+02 8.00000000e+02]
 [4.11755371e+02 7.05823669e+01 8.00000000e+02 4.07001770e+02]
 [4.11480042e+02 3.66521210e+02 7.23572449e+02 8.00000000e+02]
 [5.94662354e+02 4.15247009e+02 8.00000000e+02 8.00000000e+02]
 [2.79136932e+02 0.00000000e+00 8.00000000e+02 2.93263947e+02]
 [1.59670181e+02 9.04389114e+01 6.50252625e+02 2.89458008e+02]
 [0.00000000e+00 5.91917542e+02 3.33761322e+02 8.00000000e+02]
 [5.25089111e+02 3.84846985e+02 8.00000000e+02 6.40406250e+02]
 [2.44432739e+02 3.41828583e+02 6.69652466e+02 8.000000

[[554.5307    105.515625  800.        305.3489   ]
 [  0.        342.20554   318.0798    800.       ]
 [441.7632    105.17354   800.        288.11853  ]
 [  0.        473.57544   544.1998    800.       ]
 [511.8412    200.96822   800.        383.66098  ]
 [407.56616   460.23474   800.        800.       ]
 [247.18454   338.92722   667.3831    800.       ]
 [397.77936   565.5783    800.        800.       ]
 [281.82977     0.        800.        291.8239   ]
 [464.77612   313.9245    777.5386    800.       ]
 [ 71.24722   191.72897   589.0306    380.94916  ]
 [411.96033   371.41455   725.69904   800.       ]
 [458.4693      0.        753.59375   159.07373  ]
 [619.8973    192.01782   800.        511.1467   ]
 [594.534     413.14764   800.        800.       ]
 [  0.          0.        411.18518   358.513    ]
 [345.2344     80.01705   796.68024   297.56613  ]
 [159.9911     91.18095   656.13635   290.42282  ]
 [344.1874    385.55164   800.        741.63586  ]
 [631.3959      8.265675  800. 

[[555.36835   103.39253   800.        305.13937  ]
 [  0.        356.34894   315.24286   800.       ]
 [509.04416   196.8427    800.        381.36823  ]
 [ 60.97944   190.70927   585.04675   379.80917  ]
 [439.90683   101.0766    800.        288.05084  ]
 [408.25516   462.03705   800.        800.       ]
 [361.48853   293.38947   541.224     644.72736  ]
 [397.61118   566.72046   800.        800.       ]
 [ 96.23568   100.87892   558.91187   269.67746  ]
 [  0.         88.99522   245.54686   294.23352  ]
 [411.07864   381.5196    720.755     800.       ]
 [  0.        470.46756   537.7059    800.       ]
 [328.5542     76.21651   792.97797   300.6236   ]
 [531.2189    459.42487   800.        800.       ]
 [413.0835     70.373825  800.        409.06262  ]
 [455.96246     0.        754.26685   158.82162  ]
 [630.23596     9.166849  800.        354.2532   ]
 [  0.          0.        407.9489    356.0392   ]
 [617.9513    190.84552   800.        509.93176  ]
 [202.14285   472.85794   652.3

[[5.5604126e+02 1.0268879e+02 8.0000000e+02 3.0539056e+02]
 [0.0000000e+00 3.1051456e+02 3.2808786e+02 8.0000000e+02]
 [0.0000000e+00 4.7238522e+02 5.4852740e+02 8.0000000e+02]
 [4.0310153e+02 4.5734586e+02 8.0000000e+02 8.0000000e+02]
 [5.9012225e+02 4.0338440e+02 8.0000000e+02 8.0000000e+02]
 [3.9109055e+02 5.6386304e+02 8.0000000e+02 8.0000000e+02]
 [4.0230341e+02 3.4439682e+02 7.3464587e+02 8.0000000e+02]
 [2.7502533e+02 0.0000000e+00 8.0000000e+02 2.9618219e+02]
 [2.4256839e+02 3.2528397e+02 6.8215314e+02 8.0000000e+02]
 [4.5181464e+02 2.9128891e+02 7.7723334e+02 8.0000000e+02]
 [4.4308862e+02 9.9016983e+01 8.0000000e+02 2.9056619e+02]
 [0.0000000e+00 5.9041119e+02 3.3921313e+02 8.0000000e+02]
 [6.1804865e+02 1.9446712e+02 8.0000000e+02 5.0913406e+02]
 [5.0781952e+02 1.9523306e+02 8.0000000e+02 3.8262125e+02]
 [6.9387558e+01 1.9301913e+02 5.9087164e+02 3.8242767e+02]
 [0.0000000e+00 0.0000000e+00 4.1650476e+02 3.6332089e+02]
 [0.0000000e+00 0.0000000e+00 2.6962152e+02 5.6896039e+0

[[  0.        307.60547   331.69968   800.       ]
 [553.56915   102.34032   800.        301.5731   ]
 [402.03165   458.63486   800.        800.       ]
 [405.25702   348.76578   737.08344   800.       ]
 [391.44107   564.88403   800.        800.       ]
 [  0.        478.40396   549.58325   800.       ]
 [276.7949      0.        800.        296.12317  ]
 [  0.          0.        269.56018   586.2413   ]
 [  0.          0.        414.63116   355.6275   ]
 [590.486     412.95032   800.        800.       ]
 [404.0858     67.7436    800.        409.39755  ]
 [352.37805   378.1345    800.        752.56836  ]
 [451.01346   291.68338   776.9559    800.       ]
 [246.98372   324.74557   678.7932    800.       ]
 [103.11212   101.34188   567.452     268.94812  ]
 [616.3432    193.92065   800.        512.3213   ]
 [507.5273    195.62851   800.        384.54355  ]
 [  0.        588.94916   345.0042    800.       ]
 [385.89514   273.4272    800.        557.61584  ]
 [624.7124      6.9485664 800. 

[[553.87555  104.23119  800.       302.91498 ]
 [  0.       322.48563  327.4721   800.      ]
 [404.2362   463.5418   800.       800.      ]
 [  0.       472.68802  536.68787  800.      ]
 [412.3759   362.65778  730.2923   800.      ]
 [400.2575    61.991573 800.       408.01993 ]
 [391.09518  567.1038   800.       800.      ]
 [281.22012    0.       800.       300.36038 ]
 [  0.         0.       418.9917   356.33115 ]
 [533.7191   444.50143  800.       800.      ]
 [417.786    290.43954  619.1491   671.0445  ]
 [348.94318  370.0872   800.       746.0491  ]
 [  0.         0.       267.07455  562.5655  ]
 [248.80579  344.3424   677.90985  800.      ]
 [499.14322  192.96675  800.       387.52112 ]
 [113.239815 525.3063   747.2171   800.      ]
 [354.12286  317.58176  539.6202   714.19885 ]
 [452.1293   304.79633  768.4007   800.      ]
 [630.07196   13.455009 800.       346.7307  ]
 [435.77518   99.73559  800.       288.45923 ]
 [582.3914    86.84974  800.       494.5421  ]
 [  0.       

In [ ]:
def multiply(x):
    return x * 800


import cv2
try:
    with detection_graph.as_default():
        with tf.Session() as sess:
                # Get handles to input and output tensors
                ops = tf.get_default_graph().get_operations()
                all_tensor_names = {output.name for op in ops for output in op.outputs}
                tensor_dict = {}
                for key in [
                  'num_detections', 'detection_boxes', 'detection_scores',
                  'detection_classes', 'detection_masks'
                ]:
                    tensor_name = key + ':0'
                    if tensor_name in all_tensor_names:
                        tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
                      tensor_name)

                while True:
#                     ret, image_np = cap.read()
                    image_np = cv2.imread("crowd_2265.png")
                    # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
                    image_np_expanded = np.expand_dims(image_np, axis=0)
                    # Actual detection.
                    output_dict = run_inference_for_single_image(image_np, detection_graph)
                    coordinates = np.asarray(output_dict['detection_boxes'])*800
                    print(np.asarray(coordinates))
                    
                    cv2.rectangle(image_np, (int(coordinates[-1][1]), int(coordinates[-1][2])), (int(coordinates[-1][3]), int(coordinates[-1][0])), (255,0,0), 2)
                    # Visualization of the results of a detection.
                    vis_util.visualize_boxes_and_labels_on_image_array(
                        image_np,
                        output_dict['detection_boxes'],
                        output_dict['detection_classes'],
                        output_dict['detection_scores'],
                        category_index,
                        instance_masks=output_dict.get('detection_masks'),
                        use_normalized_coordinates=True,
                        line_thickness=8)
                    cv2.imshow('object_detection', cv2.resize(image_np, (800, 800)))
                    if cv2.waitKey(25) & 0xFF == ord('q'):
                        cap.release()
                        cv2.destroyAllWindows()
                        break
except Exception as e:
    print(e)
    cap.release()

23.14769
